ignore:
  - "hgdl/_version.py"
  - "setup.py"

coverage:
  status:
    project:
      default:
        target: auto
        paths:
          - "hgdl"
        informational: true 
    patch:
      default:
        target: auto
        paths:
          - "hgdl"
        informational: true

